from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringTaskSeries",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("frequency", models.CharField(choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly"), ("custom", "Custom")], default="daily", max_length=20)),
                ("weekdays", models.JSONField(blank=True, default=list)),
                ("daily_time_slots", models.JSONField(blank=True, default=list)),
                ("interval", models.PositiveIntegerField(default=1)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("occurrence_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("weather_warning", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recurring_task_series", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name_plural": "Recurring task series", "ordering": ["title", "start_date"]},
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(choices=[("irrigation", "Irrigation"), ("fertilizing", "Fertilizing"), ("spraying", "Spraying"), ("harvesting", "Harvesting"), ("feeding", "Feeding Animals"), ("cleaning", "Cleaning"), ("maintenance", "Maintenance"), ("transport", "Transport"), ("inspection", "Inspection"), ("general", "General")], default="general", max_length=40)),
                ("priority", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")], default="medium", max_length=10)),
                ("estimated_duration_minutes", models.PositiveIntegerField(default=60)),
                ("default_location", models.CharField(blank=True, max_length=160)),
                ("default_required_items", models.JSONField(blank=True, default=list)),
                ("default_checklist", models.JSONField(blank=True, default=list)),
                ("instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="task_templates", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="WorkerGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("members", models.ManyToManyField(blank=True, related_name="worker_groups", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="WorkTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(choices=[("irrigation", "Irrigation"), ("fertilizing", "Fertilizing"), ("spraying", "Spraying"), ("harvesting", "Harvesting"), ("feeding", "Feeding Animals"), ("cleaning", "Cleaning"), ("maintenance", "Maintenance"), ("transport", "Transport"), ("inspection", "Inspection"), ("general", "General")], default="general", max_length=40)),
                ("priority", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")], default="medium", max_length=10)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("scheduled", "Scheduled"), ("in_progress", "In Progress"), ("completed", "Completed"), ("cancelled", "Cancelled"), ("postponed", "Postponed"), ("missed", "Missed"), ("overdue", "Overdue")], default="draft", max_length=20)),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("estimated_duration_minutes", models.PositiveIntegerField(default=60)),
                ("actual_duration_minutes", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("related_entity_type", models.CharField(choices=[("field", "Field"), ("crop", "Crop"), ("livestock", "Livestock Group"), ("greenhouse", "Greenhouse"), ("equipment", "Equipment"), ("inventory", "Inventory Item"), ("other", "Other")], default="other", max_length=20)),
                ("related_entity_name", models.CharField(blank=True, max_length=160)),
                ("required_items", models.JSONField(blank=True, default=list)),
                ("instructions", models.TextField(blank=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("completion_notes", models.TextField(blank=True)),
                ("completion_proof", models.JSONField(blank=True, default=list)),
                ("weather_note", models.CharField(blank=True, max_length=200)),
                ("is_recurring", models.BooleanField(default=False)),
                ("occurrence_index", models.PositiveIntegerField(blank=True, null=True)),
                ("consumption_log", models.JSONField(blank=True, default=list)),
                ("last_status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tasks", to="api.workergroup")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_work_tasks", to=settings.AUTH_USER_MODEL)),
                ("last_status_changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="task_status_changes", to=settings.AUTH_USER_MODEL)),
                ("parent_task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dependent_tasks", to="api.worktask")),
                ("recurring_series", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="occurrences", to="api.recurringtaskseries")),
            ],
            options={"ordering": ["start_at", "priority", "title"]},
        ),
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=80)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="task_history_entries", to=settings.AUTH_USER_MODEL)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history_entries", to="api.worktask")),
            ],
            options={"verbose_name_plural": "Task history", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment_type", models.CharField(choices=[("note", "Note"), ("issue", "Issue"), ("delay", "Delay"), ("completion", "Completion")], default="note", max_length=20)),
                ("message", models.TextField()),
                ("time_spent_minutes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="task_comments", to=settings.AUTH_USER_MODEL)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="api.worktask")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TaskChecklistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("completed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="completed_checklist_items", to=settings.AUTH_USER_MODEL)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checklist_items", to="api.worktask")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("response", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected"), ("cannot_complete", "Cannot complete"), ("reschedule_requested", "Reschedule requested")], default="pending", max_length=24)),
                ("note", models.TextField(blank=True)),
                ("assigned_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_tasks_to_workers", to=settings.AUTH_USER_MODEL)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="api.worktask")),
                ("worker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_assignments", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["worker__username"], "unique_together": {("task", "worker")}},
        ),
        migrations.AddField(
            model_name="worktask",
            name="assigned_workers",
            field=models.ManyToManyField(blank=True, related_name="assigned_work_tasks", through="api.TaskAssignment", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="worktask",
            name="can_start_after",
            field=models.ManyToManyField(blank=True, related_name="unlocks", symmetrical=False, to="api.worktask"),
        ),
    ]
