# Generated by Django 5.2.13 on 2026-04-16 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'plant_stages',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='worktask',
            name='assigned_workers',
            field=models.ManyToManyField(blank=True, related_name='assigned_work_tasks', through='api.TaskAssignment', through_fields=('task', 'worker'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('size_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('size_unit', models.CharField(default='m2', max_length=20)),
                ('greenhouse_type', models.CharField(blank=True, max_length=100)),
                ('temperature_min_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_max_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity_target_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greenhouses', to='api.farm')),
            ],
            options={
                'db_table': 'greenhouses',
                'ordering': ['farm__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('variety', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity_unit', models.CharField(default='plants', max_length=30)),
                ('planted_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('harvested', 'Harvested'), ('failed', 'Failed'), ('removed', 'Removed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('greenhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='api.greenhouse')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='api.plantstage')),
            ],
            options={
                'db_table': 'plants',
                'ordering': ['name', 'variety', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HarvestHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvested_at', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_unit', models.CharField(default='kg', max_length=30)),
                ('quality_grade', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_records', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_history', to='api.plant')),
            ],
            options={
                'db_table': 'harvest_history',
                'ordering': ['-harvested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('size_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('size_unit', models.CharField(default='m2', max_length=20)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('irrigation_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='api.farm')),
            ],
            options={
                'db_table': 'plots',
                'ordering': ['farm__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='api.plot'),
        ),
        migrations.CreateModel(
            name='RecurringTaskPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('interval_value', models.PositiveIntegerField(default=1)),
                ('weekdays_text', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time_of_day', models.TimeField()),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('required_items_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_task_plans', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, db_column='last_updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_recurring_task_plans', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_series', to='api.plant')),
            ],
            options={
                'db_table': 'recurring_task_series',
                'ordering': ['title', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed_pending_confirmation', 'Completed Pending Confirmation'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=40)),
                ('scheduled_start_at', models.DateTimeField()),
                ('scheduled_end_at', models.DateTimeField()),
                ('actual_start_at', models.DateTimeField(blank=True, null=True)),
                ('worker_completed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('required_items_text', models.TextField(blank=True)),
                ('worker_note', models.TextField(blank=True)),
                ('manager_note', models.TextField(blank=True)),
                ('postponement_reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('completion_confirmation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks_v2', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, db_column='last_updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tasks_v2', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.plant')),
                ('recurring_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.recurringtaskplan')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['scheduled_start_at', 'priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResourceUsageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=120)),
                ('resource_type', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_unit', models.CharField(max_length=30)),
                ('used_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_usage', to='api.plant')),
                ('recorded_by', models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_usage_records', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_usage', to='api.task')),
            ],
            options={
                'db_table': 'resource_usage',
                'ordering': ['-used_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks_v2', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_assignments',
                'ordering': ['worker__username', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskCommentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('note', 'Note'), ('issue', 'Issue'), ('delay', 'Delay'), ('completion', 'Completion')], default='note', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments_v2', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.task')),
            ],
            options={
                'db_table': 'task_comments',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('action_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history_entries_v2', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='api.task')),
            ],
            options={
                'db_table': 'task_history',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='greenhouse',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='uq_greenhouse_name_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='harvesthistoryentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_harvest_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='plot',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='uq_plot_name_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('plot__isnull', False), ('greenhouse__isnull', True)), models.Q(('plot__isnull', True), ('greenhouse__isnull', False)), _connector='OR'), name='chk_plant_area_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.UniqueConstraint(fields=('plot',), name='uq_one_plant_per_plot'),
        ),
        migrations.AddConstraint(
            model_name='recurringtaskplan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='chk_series_end_date'),
        ),
        migrations.AddConstraint(
            model_name='recurringtaskplan',
            constraint=models.CheckConstraint(condition=models.Q(('interval_value__gt', 0)), name='chk_series_interval_positive'),
        ),
        migrations.AddConstraint(
            model_name='recurringtaskplan',
            constraint=models.CheckConstraint(condition=models.Q(('default_duration_minutes__gt', 0)), name='chk_series_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_end_at__gt', models.F('scheduled_start_at'))), name='chk_task_time_order'),
        ),
        migrations.AddConstraint(
            model_name='resourceusageentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_resource_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='taskassignmentrecord',
            constraint=models.UniqueConstraint(fields=('task', 'worker'), name='uq_task_worker'),
        ),
    ]
